### ISSUE TITLE
Message is always printed as bold regardless of configuration

### ISSUE THREAD

**Issue by abrindam** [egnyte/ax#45]
To reproduce, setup your config file colors so that messages should not be printed as bold, for example:

```
colors:
    timestamp:
        fg: cyan
    message:        
        fg: white
        bold: false
    attributekey:
        faint: true
        fg: green
    attributevalue:
        faint: true
        fg: white
```

Expected behavior: the message field should not be printed bold
Actual behavior: it is printed bold

Note: The opposite, making other fields bold, works fine.

From a quick look, this appears to be caused by a bug in the underlying "mergo" library that is used to merge the default config and the user's config. Boolean values of false are not merged. See this issue: https://github.com/imdario/mergo/issues/166
